version: '3.9'

services:
  releaser:
    build:
      context: .
      dockerfile: ./docker/releaser/Dockerfile
      args:
        SCHEDULER_MINUTES: ${SCHEDULER_MINUTES}
    restart: unless-stopped
    privileged: true
    environment:
      - SERVER
      - ORCHESTRATOR
      - GITLAB_URL
      - GITLAB_SSH
      - GITLAB_TOKEN
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_USER
      - SMTP_PASS
      - LOG_MAIL
      - LOCK_LIFETIME_MINUTES
      - AUTO_DEPLOY
      - AUTO_BACKUP
      - AUTO_SANITIZE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - .:/app
      - /app/vendor
    healthcheck:
      test: php -l /app/run.php || exit 1
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5

  mail:
    build:
      context: .
      dockerfile: ./docker/mail/Dockerfile
    restart: unless-stopped
    user: root
    expose:
      - 1025
      - 8025
    ports:
      - ${MAILHOG_PORT}:8025
    profiles:
      - development
